'use client';

import './globals.css'
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="h-[100vh] lg:bg-pantry-image bg-[100%,100%] bg-no-repeat ">{children}</body>
    </html>
  )
}
